events {}
http {
    upstream myapp {
        # This will be updated by the Jenkins pipeline
        server app_blue:8000;
    }

    server {
        listen 80;
        server_name mlolad.xyz;
        location / {
            proxy_pass http://myapp;
        }
    }
}
