events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream autoplay_backend {
        # Active environment - Swapped during deploy: app_blue or app_green
        server app_green:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://autoplay_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health endpoint for Nginx load balancer checks
        location /nginx-health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
