- name: AutoPlay Verification Setup
  hosts: hosts_127_0_0_1
  become: yes
  tasks:
    - name: Ensure custom group "devops" exists
      ansible.builtin.group:
        name: "devops"
        state: present

    - name: Create system user "verifyuser"
      ansible.builtin.user:
        name: "verifyuser"
        shell: "/bin/bash"
        groups: "devops"
        append: yes
        state: present


